### PR TITLE
Update readme to reflect new ownership

### PR DESCRIPTION
**Pull request by ablaom**
@bensadeghi If you are seeing this, perhaps you want to update your fork to redirect here, to save confusion (stop you getting PR's, for example). Or your can make your fork private.

### CODE REVIEW

**Review by bensadeghi — APPROVED** [review]
Looks good. Thanks for this.

**Comment by ablaom** [comment]
Just trying to figure out why there are not tests happening here.

**Comment by ablaom** [comment]
Ahaa. A tab character in the yml file!

**Comment by bensadeghi** [comment]
I've updated my fork's README with a message stating the packages new maintainer and home. I think that should be good enough, but if there's still some confusion, I'll make is private.

**Pull request merged**
