### PR TITLE
Round digits in `print_tree`

### PR DESCRIPTION
**Pull request by rikhuijzer**
## Before (`dev` branch)

```
Feature 3, Threshold -28.166052806422238
L-> Feature 2, Threshold -161.04351901384842
    L-> 5 : 842/3650
    R-> 7 : 2493/10555
R-> Feature 7, Threshold 108.1408338577021
    L-> 2 : 2434/15287
    R-> 8 : 1227/3508
```

## After (this PR)

```
Feature 3, Threshold -28.16
L-> Feature 2, Threshold -161.04
    L-> 5 : 842/3650
    R-> 7 : 2493/10555
R-> Feature 7, Threshold 108.14
    L-> 2 : 2434/15287
    R-> 8 : 1227/3508
```

### CODE REVIEW

**Review by ablaom — COMMENTED** [review]
This totally makes sense. My only suggestion would be to use `sigdigits` instead of `digits` in round (and name of kwarg) because  features can come with very different scales

**Comment by rikhuijzer** [comment]
> This totally makes sense. My only suggestion would be to use `sigdigits` instead of `digits` in `round` (and name of kwarg) because features can come with very different scales

I never knew of the existence of `sigdigits`. Thanks; I've updated it

**Comment by ablaom** [comment]
Thanks for the change.

I suggest we increase the default `sigdigits` to 4 or 3. `2` is probably overkill.

**Comment by ablaom** [comment]
Please rebase your PR to address the conflicts. Part of these will be because I modified the print_tree doc-string before merging #172, which I did to improve the string further and resolve a separate conflict.

**Comment by rikhuijzer** [comment]
Don't merge yet. I should add a test first

**Comment by rikhuijzer** [comment]
I've added a test in 3ba1651 and added a first argument `io::IO` to the `print_tree` signature. I figured that it would probably be best to implement that at some point anyway because it is a Julia convention, so I thought why not now.

If that feature is not acceptable, we can revert 3ba1651 and merge that. The tests do not add super much unfortunately. It's hard to test the text.

**Review by ablaom — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
