### PR TITLE
Add support for DataFrames

### PR DESCRIPTION
**Pull request by ValdarT**
Added support for DataFrames. I tried to generally keep to the original code style and make as few changes as possible (although there's still quite a lot). The change to the Node struct is there to avoid the slow Vector{Any} and to be able to return the predictions as CategoricalArrays if this was used as input.

Note that this PR does not address the issue of missing data! I think this is a separate topic especially since Missing will be part the language (in 0.7) and so missing data can be present in any Matrix.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I think the 0.6 updates should be in a separate PR. Regarding support for `DataFrames` then I think it would be better to avoid anything `DataFrames` related in the computational routines and instead just add `DataFrames` methods for `build_x` and `apply_` that just construct the relevant numerical arrays from the DataFrame and call the existing methods. That would be much simpler to manage and probably also faster.

**Comment by ValdarT** [comment]
Thanks for having a look.

>  think the 0.6 updates should be in a separate PR.

I updated because DataFrames v0.11 does not support Julia 0.5. I didn't see the harm in changing `immutable` to `struct` while I was at it.

>  just construct the relevant numerical arrays from the DataFrame and call the existing methods. That would be much simpler to manage and probably also faster.

The Arrays need not be numerical. Heterogeneous features are supported by the package (for classification) and are the most likely reason for someone using DataFrames. `Matrix{Any}` is rather slow and using DataFrames with this PR actually speeds things up considerably. It doesn’t compare that bad against `Matrix{Float64}` either...

```
using DataFrames, CSV, DecisionTree

cd("C:/Users/valda/Documents")

# dataset from https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
adult = CSV.read("adult.csv", header=[
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "marital-status",
    "occupation",
    "Priv-house-serv",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "class"
])

# convert CategoricalArray columns to Array{String}
# CategoricalArray features won't work currently due to UniqueRanges iteration
function preproc!(df::DataFrame)
    for i in 1:size(df,2)
        if isa(df[i], CategoricalArray)
            df[:,i] = string.(df[i])
        end
    end
end
preproc!(adult)

# convert DataFrame to Array{Any}
function convert_to_arr(df::DataFrame)
    out = Matrix{Any}(size(df)...)
    for i in 1:size(df,2)
        out[:,i] = Array(df[i])
    end
    out
end
mat = convert_to_arr(adult)

## Time heterogenous features
# Matrix
@time model1 = build_tree(mat[1:10, 15], mat[1:10, 1:14]) # compile
@time model1 = build_tree(mat[:, 15], mat[:, 1:14]) # test
# DataFrame
@time model2 = build_tree(adult[1:10,:], :class) # compile
@time model2 = build_tree(adult, :class) # test


## Time numeric features
numcols = eltypes(adult) .!= String
# Matrix
numcols[15] = false
labels, features = Array{String}(mat[1:10, 15]), Array{Float64}(mat[1:10, numcols]);
@time model1 = build_tree(labels, features) # compile
labels, features = Array{String}(mat[:, 15]), Array{Float64}(mat[:, numcols]);
@time model1 = build_tree(labels, features) # test
# DataFrame
numcols[15] = true
@time model2 = build_tree(adult[1:10, numcols], :class) # compile
@time model2 = build_tree(adult[numcols], :class) # test
```

**Comment by ValdarT** [comment]
Btw, the issue with CategoricalArrays as features seems to come from the custom iteration used with `UniqueRanges` that errors with CategoricalArrays. [Opened an issue](https://github.com/JuliaData/CategoricalArrays.jl/issues/119) to find out more.

**Comment by ValdarT** [comment]
I don't think this custom iteration issue can be fixed - it is coded as if generic but actually makes very specific assumptions about the way the wrapped Array returns it's state. 
If anyone has an idea how to fix it, then I still think this PR makes sense. If not, then I guess I'll just close it? 

In general I don't agree that converting into numerical Arrays is a good way of dealing with this (as direct support for categorical data is one of the unique strengths of decision trees) but merging something like this without the iteration fix seems also bad. I think a proper way of dealing with it requires a bit of code refactoring - getting rid of the wrapper and defining specific loss/split functions for different types of Arrays.

**Comment by cstjean** [comment]
Could you please point to the problematic iteration code?

**Comment by ValdarT** [comment]
Starting here: https://github.com/bensadeghi/DecisionTree.jl/blob/5f0adc5d6d0280f995ccc364e5d00a72f6387368/src/DecisionTree.jl#L58

Definition of ```next()``` is the most obviously problematic one but other two are also not generic... see ```@nalimilan's``` comment [here](https://github.com/JuliaData/CategoricalArrays.jl/issues/119).

**Comment by xiaodaigh** [comment]
Hopefully this picks up again. DataFrames.jl

**Comment by xiaodaigh** [comment]
@ValdarT do you think it makes sense to have a package call DecisionTreeUtils.jl that has your `DataFrame`s code?

**Comment by ValdarT** [comment]
I think this code is obsolete by now. The [MLJ](https://github.com/alan-turing-institute/MLJ.jl) integration supports the Tables.jl interface and hence should make it simple to use DataFrames with this library. In my opinion, the ideal would be to also support Tables (and hence also DataFrames) directly from DescisionTree.jl with direct algorithmic handling of categorical as well as missing data (which is one of the most appealing features of decision trees) but this requires extra work in the main library. Without that, however, this PR seems to add little value in my opinion.

**Comment by ablaom** [comment]
I think the preceding comment sums this up pretty well. Now closing this 3+ yr old PR. Thanks @ValdarT  for the work put into this.

**Pull request closed without merging**
