### PR TITLE
document use_multithreading keyword

### LINKED ISSUE #134: Multithreading in `apply_forrest`
I just did some test and realized that when using many threads, e.g. 32, and handling RandomForestRegressors with many trees, e.g. 1000, it is way faster to build a forest than to apply a forest to get a prediction.

I think this is due to the fact that multiple threads are used to build the forrest in parallel, however the "application" of a forest is done sequentially. Would it be conceivable to also apply a forest using multiple threads?

This this issue could also be related to [this issue](https://github.com/bensadeghi/DecisionTree.jl/issues/15)

### PR DESCRIPTION
**Pull request by rafaqz**
The keyword is currently undocumented. Closes #134

### CODE REVIEW

**Comment by ablaom** [comment]
@rafaqz Thanks for this.

It seems to me that, after all, the `use_mulithreading` option is only implemented for `apply_forest` (which returns majority votes) but was never implemented for `apply_forest_proba`. So this PR appears to document a feature that does not (but should) exist. 

In also can't find multithreading support for prediction in regression, only classification.

Would you agree with this assessment?

**Comment by rafaqz** [comment]
Oh hah sorry I just added it to the wrong method will fix

**Comment by rafaqz** [comment]
So it turns out `apply_forest` wasn't actually documented, thus the mistake in adding the docs. Can we add some docs for it? I don't actually know what to add there.

For background on this, this came up while working with a research group switching to Julia who concluded this was much slower than ScikitLearn - because this keyword is not documented and they were running it on one thread against 8 for python.

**Comment by ablaom** [comment]
This is still the wrong method - it is `apply_forest_proba`, not `apply_tree` that has the parameter. 

I agree these methods need doc-strings. Currently most of the documentation for DecisionTree.jl lives only on the README.md. 

If you want to close this and just open an new documentation issue for someone else to address, then that's fine.

**Comment by rafaqz** [comment]
No, it's this method

https://github.com/JuliaAI/DecisionTree.jl/blob/dev/src/classification/main.jl#L453

**Comment by rafaqz** [comment]
No worries, I can't finish the empty doc anyway.

But we can't really close that other issue without documenting the keyword, people can't find that it exists.

**Comment by rafaqz** [comment]
Ok this actually finally documents the right function, and seems mergeable to me.

**Review by ablaom — COMMENTED** [review]
Good to go.

**Pull request merged**
